FROM sematext/spm-client
MAINTAINER AX Carpentry <infrastructure@ax-semantics.com>

ADD monitor-template-config-es-standalone.properties /opt/spm/spm-monitor/templates/monitor-template-config-es-standalone.properties
