FROM sematext/spm-client
MAINTAINER AX Carpentry <infrastructure@ax-semantics.com>

RUN sed -i 's/localhost/es.qax.io/g' /opt/spm/spm-monitor/templates/monitor-template-config-es-standalone.properties
